In [1]:

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.preprocessing import MultiLabelBinarizer

In [2]:
def k_means(X, K, max_iterations):
     # Initialize centroids randomly
    centroids = X[np.random.choice(X.shape[0], K, replace=False)]

    for i in range(max_iterations):
        # Assign each data point to the nearest centroid
        distances = np.sqrt(((X - centroids[:, np.newaxis])**2).sum(axis=2))
        labels = np.argmin(distances, axis=0)

        # Update the centroids based on the mean of the data points in each cluster
        for k in range(K):
            centroids[k] = X[labels == k].mean(axis=0)

    return labels, centroids

In [3]:
books=pd.read_csv('OpenBook.csv')
books.head()

books.columns

# books=books[['Book Id', 'Title', 'Author', 'average_rating', 'isbn','ratings_count', 'publisher', 'Genres']]

books.head(10)
# books["Image-URL-M"][0]

books.drop_duplicates("Genres")

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Genres
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,"Fiction, Fantasy"
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"Fantasy, Fiction, Fantasy"
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,"Mystery, Fantasy, Fiction, Fantasy"
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,"Fantasy, Fiction"
5,399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,Fiction
...,...,...,...,...,...,...,...,...,...
9240,671541900,A man and two women: Stories (A Touchstone book),Doris May Lessing,1984,Simon &amp; Schuster,http://images.amazon.com/images/P/0671541900.0...,http://images.amazon.com/images/P/0671541900.0...,http://images.amazon.com/images/P/0671541900.0...,"Crime, Thriller, Novels, Mystery, Mystery, Mys..."
9249,448416492,Ice Stars (All Aboard Reading. Level 3),S. A. Kramer,1997,Grosset &amp; Dunlap,http://images.amazon.com/images/P/0448416492.0...,http://images.amazon.com/images/P/0448416492.0...,http://images.amazon.com/images/P/0448416492.0...,"Literary Fiction, Mystery"
9277,345377672,Body Count,William X. Kienzle,1993,Fawcett Books,http://images.amazon.com/images/P/0345377672.0...,http://images.amazon.com/images/P/0345377672.0...,http://images.amazon.com/images/P/0345377672.0...,"Religion, History, History, Nonfiction"
9300,789426323,The Starlight Princess and Other Princess Stories,Belinda Downes,1999,DK Ink,http://images.amazon.com/images/P/0789426323.0...,http://images.amazon.com/images/P/0789426323.0...,http://images.amazon.com/images/P/0789426323.0...,"Short Stories, Fiction, Novels, Literature, Li..."
9302,688172253,I'm Not in the Mood: What Every Woman Should K...,Judith Reichman,1999,Perennial Currents,http://images.amazon.com/images/P/0688172253.0...,http://images.amazon.com/images/P/0688172253.0...,http://images.amazon.com/images/P/0688172253.0...,"Literature, Literature, Fiction, Science Ficti..."

In [4]:
#convert the genre into binary features
books = books.dropna(subset=['Genres'])
genres = books['Genres'].str.split(',')
mlb = MultiLabelBinarizer()
genres_encoded = pd.DataFrame(mlb.fit_transform(genres), columns=mlb.classes_)
genres_encoded

,AUTOBIOGRAPHY,Action,Adult,Adult Fiction,American History,Art,Asian Literature,Autobiography,Biblical,Biography,...,Romance,Science Fiction,Short Stories,Sociology,Spirit,Suspense,Thriller,War,World War I,World War II
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
K = 100
max_iterations = 100
labels, centroids = k_means(genres_encoded.values, K, max_iterations)
books['Genre Cluster'] = labels
def recommend_books(book_name):
    book_cluster = books.loc[books['Book-Title'] == book_name, 'Genre Cluster'].values[0]
    recommended_books = books.loc[books['Genre Cluster'] == book_cluster, ['Book-Title','Book-Author', 'Publisher','Image-URL-M']]
    return recommended_books.head(5)

recommend_books('The Lord of the Rings')

C:\Users\ACER\AppData\Local\Temp\ipykernel_3732\1509054709.py:12: RuntimeWarning: Mean of empty slice.
  centroids[k] = X[labels == k].mean(axis=0)
C:\Users\ACER\anaconda3\lib\site-packages\numpy\core\_methods.py:182: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(

,Book-Title,Book-Author,Publisher,Image-URL-M
47,Isle of Dogs,Patricia Cornwell,Berkley Publishing Group,http://images.amazon.com/images/P/0425182908.0...
61,Shabanu: Daughter of the Wind (Border Trilogy),SUZANNE FISHER STAPLES,Laurel Leaf,http://images.amazon.com/images/P/0679810307.0...
69,The Angel Is Near,Deepak Chopra,St. Martin's Press,http://images.amazon.com/images/P/0312970242.0...
70,Tess of the D'Urbervilles (Wordsworth Classics),Thomas Hardy,NTC/Contemporary Publishing Company,http://images.amazon.com/images/P/1853260053.0...
72,The Accidental Virgin,Valerie Frankel,Avon Trade,http://images.amazon.com/images/P/0060938412.0...

In [10]:
import pickle
pickle.dump(books, open('book.pkl', 'wb'))